name: build
on:
- push

jobs:
  build-linux-static:
    name: Build (Linux static)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install system dependencies
        run: sudo apt install musl-tools lld
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          mkdir dist
          cp target/x86_64-unknown-linux-musl/release/lazyproxy ./dist/
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: linux-static
          path: ./dist
  build-macos:
    name: Build (macOS)
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build
        run: |
          cargo build --release
          mkdir dist
          cp target/release/lazyproxy ./dist/
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: ./dist
  release:
    name: Create release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    needs:
      - build-linux-static
      - build-macos
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: linux-static
          path: ./dist/linux-static
      - uses: actions/download-artifact@v2
        with:
          name: macos
          path: ./dist/macos
      - name: Cleanup
        run: |
          cd dist
          mkdir packages
          cp ./linux-static/lazyproxy ./packages/lazyproxy.linux-static
          cp ./macos/lazyproxy ./packages/lazyproxy.macos
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/packages/lazyproxy.linux-static
            dist/packages/lazyproxy.macos
